// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp3.Data;

#nullable disable

namespace MyWebApp3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630155152_RemoveIsDonePropertyFromBook")]
    partial class RemoveIsDonePropertyFromBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWebApp3.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dale Carnegie",
                            Title = "Đắc Nhân Tâm",
                            YearPublished = 1936
                        },
                        new
                        {
                            Id = 2,
                            Author = "Paulo Coelho",
                            Title = "Nhà Giả Kim",
                            YearPublished = 1988
                        },
                        new
                        {
                            Id = 3,
                            Author = "Robert Kiyosaki",
                            Title = "Cha Giàu Cha Nghèo",
                            YearPublished = 1997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
